---
kind: Service
apiVersion: v1
metadata:
  name: ghost
  namespace: maxgio-prod
  labels:
    app: ghost
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 2368
  selector:
    app: ghost
  type: ClusterIP
