apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-1.81.0.tgz
  valuesContent: |-
    rbac:
      enabled: true
    ssl:
      enabled: true
    metrics:
      prometheus:
        enabled: true
    kubernetes:
      ingressEndpoint:
        useDefaultPublishedService: true
    ssl.enabled: "true"
    ssl.insecureSkipVerify: "true" 
    metrics.prometheus.enabled: "true"
    metrics.serviceMonitor.enabled: "true" 
    dashboard.enabled: "true"
    dashboard.serviceType: "LoadBalancer"
    dashboard.auth.basic.admin: "$apr1$tM.asdgfs$kljkuwd" 
    loadBalancerIP: 192.168.1.30
    logLevel: "debug"
    image: "rancher/library-traefik"
    tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
