apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
 name: letsencrypt
spec:
 acme:
   server: https://acme-v02.api.letsencrypt.org/directory
   email: massimiliano.giovagnoli.1992@gmail.com
   privateKeySecretRef:
     name: letsencrypt
   solvers:
   - http01:
       ingress:
         class: traefik
